name: Code Checks

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  lint:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-26, ubuntu-24.04, ubuntu-24.04-arm]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v6.0.2

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: make clippy
